"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, ShieldCheck } from "lucide-react";
import { ArchitecturePolicy } from "@/lib/types";

const initial: ArchitecturePolicy = { organization: "personal", requireCi: true, requireTestEvidence: true, maxDependencies: 80, maxComplexity: 70 };

export default function GovernancePage() {
    const [policy, setPolicy] = useState(initial);
    const [saving, setSaving] = useState(false);
    const [saved, setSaved] = useState(false);
    useEffect(() => { fetch("/api/policy?organization=personal").then((response) => response.json()).then(setPolicy).catch(() => undefined); }, []);
    const save = async () => { setSaving(true); setSaved(false); try { const response = await fetch("/api/policy", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(policy) }); if (!response.ok) throw new Error(); setSaved(true); } finally { setSaving(false); } };
    return <div className="mx-auto w-full max-w-3xl px-5 py-12 sm:px-8"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/5 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-300"><ShieldCheck className="h-3.5 w-3.5" /> Governance baseline</div><h1 className="mt-5 text-4xl font-bold tracking-tight">Architecture policy</h1><p className="mt-3 max-w-2xl text-zinc-400">Every scan is evaluated against these guardrails. Policy breaches are surfaced in the executive report and CLI output.</p><div className="mt-10 space-y-5 rounded-3xl border border-white/10 bg-slate-900/45 p-6 sm:p-8"><label className="block"><span className="text-xs font-bold uppercase tracking-wider text-zinc-400">Workspace</span><input value={policy.organization} disabled className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-zinc-500" /></label><Toggle label="Require CI workflow" description="Flag repositories without detectable GitHub Actions workflows." checked={policy.requireCi} onChange={(requireCi) => setPolicy({ ...policy, requireCi })} /><Toggle label="Require test evidence" description="Flag repositories without conventional test paths or filenames." checked={policy.requireTestEvidence} onChange={(requireTestEvidence) => setPolicy({ ...policy, requireTestEvidence })} /><div className="grid gap-5 sm:grid-cols-2"><NumberField label="Dependency budget" value={policy.maxDependencies} max={500} onChange={(maxDependencies) => setPolicy({ ...policy, maxDependencies })} /><NumberField label="Complexity budget" value={policy.maxComplexity} max={100} onChange={(maxComplexity) => setPolicy({ ...policy, maxComplexity })} /></div><button onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-xs font-bold text-slate-950 disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : saved ? <CheckCircle2 className="h-4 w-4" /> : null}{saved ? "Policy saved" : "Save policy"}</button></div></div>;
}
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-2xl border border-white/5 bg-white/[0.025] p-4"><span><span className="block text-sm font-semibold text-zinc-200">{label}</span><span className="mt-1 block text-xs text-zinc-500">{description}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-cyan-300" /></label>; }
function NumberField({ label, value, max, onChange }: { label: string; value: number; max: number; onChange: (value: number) => void }) { return <label><span className="text-xs font-bold uppercase tracking-wider text-zinc-400">{label}</span><input type="number" min="1" max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-zinc-100 outline-none focus:border-cyan-400/50" /></label>; }
